supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dHdsb2Jmd3lzcGtxeWhocGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NzQ1OTIsImV4cCI6MjA3NjA1MDU5Mn0.cPcPXDclddkGkAcJWRwfcMsCQmz-U0bxirMbakc40MQ"
supabase_url = "https://kttwlobfwyspkqyhhpis.supabase.co"

password = "12345"

[passwords]
username = "user123"
